/// Mapping of timezone offsets (in minutes) to timezone names
const Map<int, List<String>> offsetToTimezones = {
  0: [
    'Africa/Abidjan',
    'Africa/Accra',
    'Africa/Bamako',
    'Africa/Banjul',
    'Africa/Bissau',
    'Africa/Conakry',
    'Africa/Dakar',
    'Africa/Freetown',
    'Africa/Lome',
    'Africa/Monrovia',
    'Africa/Nouakchott',
    'Africa/Ouagadougou',
    'Africa/Sao_Tome',
    'Africa/Timbuktu',
    'America/Danmarkshavn',
    'Atlantic/Reykjavik',
    'Atlantic/St_Helena',
    'Etc/GMT',
    'Etc/GMT+0',
    'Etc/GMT-0',
    'Etc/GMT0',
    'Etc/Greenwich',
    'Etc/UCT',
    'Etc/UTC',
    'Etc/Universal',
    'Etc/Zulu'
  ],
  60: [
    'Africa/Algiers',
    'Africa/Bangui',
    'Africa/Brazzaville',
    'Africa/Ceuta',
    'Africa/Douala',
    'Africa/Kinshasa',
    'Africa/Lagos',
    'Africa/Libreville',
    'Africa/Luanda',
    'Africa/Malabo',
    'Africa/Ndjamena',
    'Africa/Niamey',
    'Africa/Porto-Novo',
    'Africa/Tunis',
    'Arctic/Longyearbyen',
    'Europe/Amsterdam',
    'Europe/Andorra',
    'Europe/Belgrade',
    'Europe/Berlin',
    'Europe/Bratislava',
    'Europe/Brussels',
    'Europe/Budapest',
    'Europe/Copenhagen',
    'Europe/Gibraltar',
    'Europe/Ljubljana',
    'Europe/Luxembourg',
    'Europe/Madrid',
    'Europe/Malta',
    'Europe/Monaco',
    'Europe/Oslo',
    'Europe/Paris',
    'Europe/Podgorica',
    'Europe/Prague',
    'Europe/Rome',
    'Europe/San_Marino',
    'Europe/Sarajevo',
    'Europe/Skopje',
    'Europe/Stockholm',
    'Europe/Tirane',
    'Europe/Vaduz',
    'Europe/Vatican',
    'Europe/Vienna',
    'Europe/Warsaw',
    'Europe/Zagreb',
    'Europe/Zurich'
  ],
  120: [
    'Africa/Blantyre',
    'Africa/Bujumbura',
    'Africa/Cairo',
    'Africa/Gaborone',
    'Africa/Harare',
    'Africa/Johannesburg',
    'Africa/Kigali',
    'Africa/Lubumbashi',
    'Africa/Lusaka',
    'Africa/Maputo',
    'Africa/Maseru',
    'Africa/Mbabane',
    'Africa/Tripoli',
    'Asia/Amman',
    'Asia/Beirut',
    'Asia/Damascus',
    'Asia/Gaza',
    'Asia/Hebron',
    'Asia/Istanbul',
    'Asia/Jerusalem',
    'Asia/Nicosia',
    'Asia/Tel_Aviv',
    'Europe/Athens',
    'Europe/Bucharest',
    'Europe/Chisinau',
    'Europe/Helsinki',
    'Europe/Kiev',
    'Europe/Mariehamn',
    'Europe/Riga',
    'Europe/Sofia',
    'Europe/Tallinn',
    'Europe/Uzhgorod',
    'Europe/Vilnius',
    'Europe/Zaporozhye'
  ],
  180: [
    'Africa/Addis_Ababa',
    'Africa/Asmara',
    'Africa/Asmera',
    'Africa/Dar_es_Salaam',
    'Africa/Djibouti',
    'Africa/Juba',
    'Africa/Kampala',
    'Africa/Khartoum',
    'Africa/Mogadishu',
    'Africa/Nairobi',
    'Antarctica/Syowa',
    'Asia/Aden',
    'Asia/Baghdad',
    'Asia/Bahrain',
    'Asia/Kuwait',
    'Asia/Qatar',
    'Asia/Riyadh',
    'Europe/Istanbul',
    'Europe/Kaliningrad',
    'Europe/Minsk',
    'Europe/Moscow',
    'Europe/Simferopol',
    'Europe/Volgograd',
    'Indian/Antananarivo',
    'Indian/Comoro',
    'Indian/Mayotte'
  ],
  210: ['Asia/Tehran'],
  240: [
    'Asia/Baku',
    'Asia/Dubai',
    'Asia/Muscat',
    'Asia/Tbilisi',
    'Asia/Yerevan',
    'Europe/Samara',
    'Indian/Mahe',
    'Indian/Mauritius',
    'Indian/Reunion'
  ],
  270: ['Asia/Kabul'],
  300: [
    'Antarctica/Mawson',
    'Asia/Aqtau',
    'Asia/Aqtobe',
    'Asia/Ashgabat',
    'Asia/Ashkhabad',
    'Asia/Dushanbe',
    'Asia/Karachi',
    'Asia/Oral',
    'Asia/Samarkand',
    'Asia/Tashkent',
    'Asia/Yekaterinburg',
    'Indian/Kerguelen',
    'Indian/Maldives'
  ],
  330: ['Asia/Colombo', 'Asia/Kolkata'],
  345: ['Asia/Kathmandu', 'Asia/Katmandu'],
  360: [
    'Antarctica/Vostok',
    'Asia/Almaty',
    'Asia/Bishkek',
    'Asia/Dacca',
    'Asia/Dhaka',
    'Asia/Kashgar',
    'Asia/Novosibirsk',
    'Asia/Omsk',
    'Asia/Qyzylorda',
    'Asia/Thimbu',
    'Asia/Thimphu',
    'Asia/Urumqi',
    'Indian/Chagos'
  ],
  390: ['Asia/Rangoon'],
  420: [
    'Antarctica/Davis',
    'Asia/Bangkok',
    'Asia/Ho_Chi_Minh',
    'Asia/Hovd',
    'Asia/Jakarta',
    'Asia/Krasnoyarsk',
    'Asia/Novokuznetsk',
    'Asia/Phnom_Penh',
    'Asia/Pontianak',
    'Asia/Saigon',
    'Asia/Vientiane',
    'Indian/Christmas'
  ],
  480: [
    'Antarctica/Casey',
    'Asia/Brunei',
    'Asia/Chita',
    'Asia/Choibalsan',
    'Asia/Chongqing',
    'Asia/Chungking',
    'Asia/Harbin',
    'Asia/Hong_Kong',
    'Asia/Irkutsk',
    'Asia/Kuala_Lumpur',
    'Asia/Kuching',
    'Asia/Macao',
    'Asia/Macau',
    'Asia/Makassar',
    'Asia/Manila',
    'Asia/Shanghai',
    'Asia/Singapore',
    'Asia/Taipei',
    'Asia/Ujung_Pandang',
    'Australia/Perth',
    'Australia/West'
  ],
  510: ['Asia/Pyongyang', 'Asia/Seoul'],
  525: ['Australia/Eucla'],
  540: [
    'Asia/Dili',
    'Asia/Jayapura',
    'Asia/Khandyga',
    'Asia/Tokyo',
    'Asia/Yakutsk',
    'Pacific/Palau'
  ],
  570: [
    'Australia/Adelaide',
    'Australia/Broken_Hill',
    'Australia/Darwin',
    'Australia/North',
    'Australia/South',
    'Australia/Yancowinna'
  ],
  600: [
    'Antarctica/DumontDUrville',
    'Asia/Sakhalin',
    'Asia/Vladivostok',
    'Australia/ACT',
    'Australia/Brisbane',
    'Australia/Canberra',
    'Australia/Currie',
    'Australia/Hobart',
    'Australia/Lindeman',
    'Australia/Melbourne',
    'Australia/NSW',
    'Australia/Queensland',
    'Australia/Sydney',
    'Australia/Tasmania',
    'Australia/Victoria',
    'Pacific/Guam',
    'Pacific/Port_Moresby',
    'Pacific/Saipan'
  ],
  630: ['Australia/LHI', 'Australia/Lord_Howe'],
  660: [
    'Asia/Magadan',
    'Asia/Srednekolymsk',
    'Pacific/Bougainville',
    'Pacific/Efate',
    'Pacific/Guadalcanal',
    'Pacific/Kosrae',
    'Pacific/Noumea',
    'Pacific/Ponape'
  ],
  720: [
    'Antarctica/McMurdo',
    'Antarctica/South_Pole',
    'Asia/Anadyr',
    'Asia/Kamchatka',
    'Pacific/Auckland',
    'Pacific/Fiji',
    'Pacific/Funafuti',
    'Pacific/Kwajalein',
    'Pacific/Majuro',
    'Pacific/Nauru',
    'Pacific/Norfolk',
    'Pacific/Tarawa',
    'Pacific/Wake',
    'Pacific/Wallis'
  ],
  765: ['Pacific/Chatham'],
  780: ['Pacific/Apia', 'Pacific/Enderbury', 'Pacific/Fakaofo'],
  840: ['Pacific/Kiritimati'],
  -60: ['Atlantic/Azores', 'Atlantic/Cape_Verde', 'America/Scoresbysund'],
  -120: ['America/Noronha', 'Atlantic/South_Georgia'],
  -180: [
    'America/Araguaina',
    'America/Bahia',
    'America/Belem',
    'America/Cayenne',
    'America/Fortaleza',
    'America/Godthab',
    'America/Maceio',
    'America/Miquelon',
    'America/Montevideo',
    'America/Paramaribo',
    'America/Recife',
    'America/Santarem',
    'America/Sao_Paulo'
  ],
  -210: ['America/St_Johns'],
  -240: [
    'America/Anguilla',
    'America/Antigua',
    'America/Aruba',
    'America/Barbados',
    'America/Blanc-Sablon',
    'America/Boa_Vista',
    'America/Curacao',
    'America/Dominica',
    'America/Glace_Bay',
    'America/Goose_Bay',
    'America/Grenada',
    'America/Guadeloupe',
    'America/Guyana',
    'America/Halifax',
    'America/Kralendijk',
    'America/La_Paz',
    'America/Lower_Princes',
    'America/Manaus',
    'America/Marigot',
    'America/Martinique',
    'America/Moncton',
    'America/Montserrat',
    'America/Port_of_Spain',
    'America/Porto_Velho',
    'America/Puerto_Rico',
    'America/Santo_Domingo',
    'America/St_Barthelemy',
    'America/St_Kitts',
    'America/St_Lucia',
    'America/St_Thomas',
    'America/St_Vincent',
    'America/Thule',
    'America/Tortola',
    'America/Virgin',
    'Atlantic/Bermuda'
  ],
  -270: ['America/Caracas'],
  -300: [
    'America/Atikokan',
    'America/Bogota',
    'America/Cancun',
    'America/Cayman',
    'America/Coral_Harbour',
    'America/Detroit',
    'America/Eirunepe',
    'America/Fort_Wayne',
    'America/Grand_Turk',
    'America/Guayaquil',
    'America/Havana',
    'America/Indiana/Indianapolis',
    'America/Indiana/Marengo',
    'America/Indiana/Petersburg',
    'America/Indiana/Vevay',
    'America/Indiana/Vincennes',
    'America/Indiana/Winamac',
    'America/Indianapolis',
    'America/Iqaluit',
    'America/Jamaica',
    'America/Kentucky/Louisville',
    'America/Kentucky/Monticello',
    'America/Lima',
    'America/Louisville',
    'America/Montreal',
    'America/Nassau',
    'America/New_York',
    'America/Nipigon',
    'America/Panama',
    'America/Pangnirtung',
    'America/Port-au-Prince',
    'America/Rio_Branco',
    'America/Thunder_Bay',
    'America/Toronto'
  ],
  -360: [
    'America/Belize',
    'America/Chicago',
    'America/Costa_Rica',
    'America/El_Salvador',
    'America/Guatemala',
    'America/Indiana/Knox',
    'America/Indiana/Tell_City',
    'America/Knox_IN',
    'America/Managua',
    'America/Matamoros',
    'America/Menominee',
    'America/Merida',
    'America/Mexico_City',
    'America/Monterrey',
    'America/North_Dakota/Beulah',
    'America/North_Dakota/Center',
    'America/North_Dakota/New_Salem',
    'America/Rainy_River',
    'America/Rankin_Inlet',
    'America/Regina',
    'America/Swift_Current',
    'America/Tegucigalpa',
    'America/Winnipeg'
  ],
  -420: [
    'America/Boise',
    'America/Cambridge_Bay',
    'America/Chihuahua',
    'America/Creston',
    'America/Dawson_Creek',
    'America/Denver',
    'America/Edmonton',
    'America/Fort_Nelson',
    'America/Hermosillo',
    'America/Inuvik',
    'America/Mazatlan',
    'America/Ojinaga',
    'America/Phoenix',
    'America/Shiprock',
    'America/Yellowknife'
  ],
  -480: [
    'America/Dawson',
    'America/Los_Angeles',
    'America/Tijuana',
    'America/Vancouver',
    'America/Whitehorse',
    'Pacific/Pitcairn'
  ],
  -540: [
    'America/Anchorage',
    'America/Juneau',
    'America/Nome',
    'America/Sitka',
    'America/Yakutat'
  ],
  -600: ['America/Adak', 'America/Atka', 'Pacific/Honolulu'],
  -660: ['Pacific/Midway', 'Pacific/Niue', 'Pacific/Pago_Pago']
};

/// Mapping of timezone names to their respective country codes
const Map<String, String> timezoneToCountry = {
  'Europe/Andorra': 'AD',
  'Asia/Dubai': 'AE',
  'Asia/Kabul': 'AF',
  'America/Antigua': 'AG',
  'America/Anguilla': 'AI',
  'Europe/Tirane': 'AL',
  'Asia/Yerevan': 'AM',
  'Africa/Luanda': 'AO',
  'Antarctica/McMurdo': 'AQ',
  'America/Argentina/Buenos_Aires': 'AR',
  'Pacific/Pago_Pago': 'AS',
  'Europe/Vienna': 'AT',
  'Australia/Sydney': 'AU',
  'America/Aruba': 'AW',
  'Europe/Mariehamn': 'AX',
  'Asia/Baku': 'AZ',
  'Europe/Sarajevo': 'BA',
  'America/Barbados': 'BB',
  'Asia/Dhaka': 'BD',
  'Europe/Brussels': 'BE',
  'Africa/Ouagadougou': 'BF',
  'Europe/Sofia': 'BG',
  'Asia/Bahrain': 'BH',
  'Africa/Bujumbura': 'BI',
  'Africa/Porto-Novo': 'BJ',
  'America/St_Barthelemy': 'BL',
  'Atlantic/Bermuda': 'BM',
  'Asia/Brunei': 'BN',
  'America/La_Paz': 'BO',
  'America/Kralendijk': 'BQ',
  'America/Noronha': 'BR',
  'America/Nassau': 'BS',
  'Asia/Thimphu': 'BT',
  'Africa/Gaborone': 'BW',
  'Europe/Minsk': 'BY',
  'America/Belize': 'BZ',
  'America/St_Johns': 'CA',
  'Indian/Cocos': 'CC',
  'Africa/Kinshasa': 'CD',
  'Africa/Bangui': 'CF',
  'Africa/Brazzaville': 'CG',
  'Europe/Zurich': 'CH',
  'Africa/Abidjan': 'CI',
  'Pacific/Rarotonga': 'CK',
  'America/Santiago': 'CL',
  'Africa/Douala': 'CM',
  'Asia/Shanghai': 'CN',
  'America/Bogota': 'CO',
  'America/Costa_Rica': 'CR',
  'America/Havana': 'CU',
  'Atlantic/Cape_Verde': 'CV',
  'America/Curacao': 'CW',
  'Indian/Christmas': 'CX',
  'Asia/Nicosia': 'CY',
  'Europe/Prague': 'CZ',
  'Europe/Berlin': 'DE',
  'Africa/Djibouti': 'DJ',
  'Europe/Copenhagen': 'DK',
  'America/Dominica': 'DM',
  'America/Santo_Domingo': 'DO',
  'Africa/Algiers': 'DZ',
  'America/Guayaquil': 'EC',
  'Europe/Tallinn': 'EE',
  'Africa/Cairo': 'EG',
  'Africa/El_Aaiun': 'EH',
  'Africa/Asmara': 'ER',
  'Europe/Madrid': 'ES',
  'Africa/Addis_Ababa': 'ET',
  'Europe/Helsinki': 'FI',
  'Pacific/Fiji': 'FJ',
  'Atlantic/Stanley': 'FK',
  'Pacific/Chuuk': 'FM',
  'Atlantic/Faroe': 'FO',
  'Europe/Paris': 'FR',
  'Africa/Libreville': 'GA',
  'Europe/London': 'GB',
  'America/Grenada': 'GD',
  'Asia/Tbilisi': 'GE',
  'America/Cayenne': 'GF',
  'Europe/Guernsey': 'GG',
  'Africa/Accra': 'GH',
  'Europe/Gibraltar': 'GI',
  'America/Godthab': 'GL',
  'Africa/Banjul': 'GM',
  'Africa/Conakry': 'GN',
  'America/Guadeloupe': 'GP',
  'Africa/Malabo': 'GQ',
  'Europe/Athens': 'GR',
  'Atlantic/South_Georgia': 'GS',
  'America/Guatemala': 'GT',
  'Pacific/Guam': 'GU',
  'Africa/Bissau': 'GW',
  'America/Guyana': 'GY',
  'Asia/Hong_Kong': 'HK',
  'America/Tegucigalpa': 'HN',
  'Europe/Zagreb': 'HR',
  'America/Port-au-Prince': 'HT',
  'Europe/Budapest': 'HU',
  'Asia/Jakarta': 'ID',
  'Europe/Dublin': 'IE',
  'Asia/Jerusalem': 'IL',
  'Europe/Isle_of_Man': 'IM',
  'Asia/Kolkata': 'IN',
  'Indian/Chagos': 'IO',
  'Asia/Baghdad': 'IQ',
  'Asia/Tehran': 'IR',
  'Atlantic/Reykjavik': 'IS',
  'Europe/Rome': 'IT',
  'Europe/Jersey': 'JE',
  'America/Jamaica': 'JM',
  'Asia/Amman': 'JO',
  'Asia/Tokyo': 'JP',
  'Africa/Nairobi': 'KE',
  'Asia/Bishkek': 'KG',
  'Asia/Phnom_Penh': 'KH',
  'Pacific/Tarawa': 'KI',
  'Indian/Comoro': 'KM',
  'America/St_Kitts': 'KN',
  'Asia/Pyongyang': 'KP',
  'Asia/Seoul': 'KR',
  'Asia/Kuwait': 'KW',
  'America/Cayman': 'KY',
  'Asia/Almaty': 'KZ',
  'Asia/Vientiane': 'LA',
  'Asia/Beirut': 'LB',
  'America/St_Lucia': 'LC',
  'Europe/Vaduz': 'LI',
  'Asia/Colombo': 'LK',
  'Africa/Monrovia': 'LR',
  'Africa/Maseru': 'LS',
  'Europe/Vilnius': 'LT',
  'Europe/Luxembourg': 'LU',
  'Europe/Riga': 'LV',
  'Africa/Tripoli': 'LY',
  'Africa/Casablanca': 'MA',
  'Europe/Monaco': 'MC',
  'Europe/Chisinau': 'MD',
  'Europe/Podgorica': 'ME',
  'America/Marigot': 'MF',
  'Indian/Antananarivo': 'MG',
  'Pacific/Majuro': 'MH',
  'Europe/Skopje': 'MK',
  'Africa/Bamako': 'ML',
  'Asia/Rangoon': 'MM',
  'Asia/Ulaanbaatar': 'MN',
  'Asia/Macau': 'MO',
  'Pacific/Saipan': 'MP',
  'America/Martinique': 'MQ',
  'Africa/Nouakchott': 'MR',
  'America/Montserrat': 'MS',
  'Europe/Malta': 'MT',
  'Indian/Mauritius': 'MU',
  'Indian/Maldives': 'MV',
  'Africa/Blantyre': 'MW',
  'America/Mexico_City': 'MX',
  'Asia/Kuala_Lumpur': 'MY',
  'Africa/Maputo': 'MZ',
  'Africa/Windhoek': 'NA',
  'Pacific/Noumea': 'NC',
  'Africa/Niamey': 'NE',
  'Pacific/Norfolk': 'NF',
  'Africa/Lagos': 'NG',
  'America/Managua': 'NI',
  'Europe/Amsterdam': 'NL',
  'Europe/Oslo': 'NO',
  'Asia/Kathmandu': 'NP',
  'Pacific/Nauru': 'NR',
  'Pacific/Niue': 'NU',
  'Pacific/Auckland': 'NZ',
  'Asia/Muscat': 'OM',
  'America/Panama': 'PA',
  'America/Lima': 'PE',
  'Pacific/Tahiti': 'PF',
  'Pacific/Port_Moresby': 'PG',
  'Asia/Manila': 'PH',
  'Asia/Karachi': 'PK',
  'Europe/Warsaw': 'PL',
  'America/Miquelon': 'PM',
  'Pacific/Pitcairn': 'PN',
  'America/Puerto_Rico': 'PR',
  'Asia/Gaza': 'PS',
  'Europe/Lisbon': 'PT',
  'Pacific/Palau': 'PW',
  'America/Asuncion': 'PY',
  'Asia/Qatar': 'QA',
  'Indian/Reunion': 'RE',
  'Europe/Bucharest': 'RO',
  'Europe/Belgrade': 'RS',
  'Europe/Moscow': 'RU',
  'Africa/Kigali': 'RW',
  'Asia/Riyadh': 'SA',
  'Pacific/Guadalcanal': 'SB',
  'Indian/Mahe': 'SC',
  'Africa/Khartoum': 'SD',
  'Europe/Stockholm': 'SE',
  'Asia/Singapore': 'SG',
  'Atlantic/St_Helena': 'SH',
  'Europe/Ljubljana': 'SI',
  'Arctic/Longyearbyen': 'SJ',
  'Europe/Bratislava': 'SK',
  'Africa/Freetown': 'SL',
  'Europe/San_Marino': 'SM',
  'Africa/Dakar': 'SN',
  'Africa/Mogadishu': 'SO',
  'America/Paramaribo': 'SR',
  'Africa/Juba': 'SS',
  'Africa/Sao_Tome': 'ST',
  'America/El_Salvador': 'SV',
  'America/Lower_Princes': 'SX',
  'Asia/Damascus': 'SY',
  'Africa/Mbabane': 'SZ',
  'America/Grand_Turk': 'TC',
  'Africa/Ndjamena': 'TD',
  'Indian/Kerguelen': 'TF',
  'Africa/Lome': 'TG',
  'Asia/Bangkok': 'TH',
  'Asia/Dushanbe': 'TJ',
  'Pacific/Fakaofo': 'TK',
  'Asia/Dili': 'TL',
  'Asia/Ashgabat': 'TM',
  'Africa/Tunis': 'TN',
  'Pacific/Tongatapu': 'TO',
  'Europe/Istanbul': 'TR',
  'America/Port_of_Spain': 'TT',
  'Pacific/Funafuti': 'TV',
  'Asia/Taipei': 'TW',
  'Africa/Dar_es_Salaam': 'TZ',
  'Europe/Kiev': 'UA',
  'Africa/Kampala': 'UG',
  'Pacific/Wake': 'UM',
  'America/New_York': 'US',
  'America/Montevideo': 'UY',
  'Asia/Tashkent': 'UZ',
  'Europe/Vatican': 'VA',
  'America/St_Vincent': 'VC',
  'America/Caracas': 'VE',
  'America/Tortola': 'VG',
  'America/St_Thomas': 'VI',
  'Asia/Ho_Chi_Minh': 'VN',
  'Pacific/Efate': 'VU',
  'Pacific/Wallis': 'WF',
  'Pacific/Apia': 'WS',
  'Asia/Aden': 'YE',
  'Indian/Mayotte': 'YT',
  'Africa/Johannesburg': 'ZA',
  'Africa/Lusaka': 'ZM',
  'Africa/Harare': 'ZW',
};
